apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sa-fe-b-official-site
  name: sa-fe-b-official-site
spec:
  selector:
    matchLabels:
      app: sa-fe-b-official-site
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sa-fe-b-official-site
    spec:
      containers:
        - image: >-
            registry-vpc.cn-hangzhou.aliyuncs.com/shopastro/sa-fe-b-official-site:ad5d9eaa02512a17f818cc4e4ccbdb95b2245a96
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: sa-fe-b-official-site
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 80
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30


---
kind: Service
apiVersion: v1
metadata:
  name:  sa-fe-b-official-site
spec:
  selector:
    app.kubernetes.io/instance:  sa-fe-b-official-site
  type: ClusterIP
  ports:
    - name:  http
      port:  80
      targetPort:  80
