apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sa-fe-b-official-site
  name: sa-fe-b-official-site
spec:
  selector:
    matchLabels:
      app: sa-fe-b-official-site
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sa-fe-b-official-site
    spec:
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/shopastro/sa-fe-b-official-site:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: sa-fe-b-official-site
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 10
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30


---
kind: Service
apiVersion: v1
metadata:
  name:  sa-fe-b-official-site
spec:
  selector:
    app: sa-fe-b-official-site
  type: ClusterIP
  ports:
    - name:  http
      port:  80
      targetPort:  3000
